### ISSUE TITLE
Document minimal Qt version

### ISSUE THREAD

**Issue by initramfs** [initramfs/Test-Import-Repo#70]
Search on GitHub or grepping sources for `Qt5`, `Qt4` or something similar gives no results.

Trying to compile with `Qt 4.8.6`.

```bash
$ qmake
Project MESSAGE: Warning: unknown QT: multimediawidgets
```

```bash
$ make
...
In file included from widget/form/addfriendform.cpp:1:0:
widget/form/addfriendform.h:11:22: fatal error: QDnsLookup: No such file or directory
 #include <QDnsLookup>
...
```

[Official documentation](https://qt-project.org/doc/qt-5/qdnslookup.html) says that `QDnsLookup` is available since `Qt 5.0`.

So *toxgui* seems to require at least `Qt 5.0`, but it's not stated anywhere explicitly.
